### ISSUE TITLE
Regarding usage of 100x lr for NDDR layers

### ISSUE THREAD

**Issue by rohitgajawada** [ethanygao/NDDR-CNN#1]
Hi, thank you for your implementation. In your paper, you use a higher learning rate (like 100x) for your NDDR layers but I could not see this being done in your implementation. Is there any particular reason this change exists?

**Comment by ethanygao** [comment]
Hi @rohitgajawada, thanks for your interest. We do have used 100x lr for the NDDR layers for all of our experiments. Please find them in the running scripts in the `experiments` folder, for example:
https://github.com/ethanygao/NDDR-CNN/blob/master/experiments/VGG16/NDDR.sh#L19
